sudo: required
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - libusb-dev
      - libusb-1.0-0-dev
      - libudev-dev
      - python-dbus
      - libffi-dev
      - liblua5.2-dev
      - libjpeg8-dev
      - pyside-tools
      - pyqt4-dev-tools
      - pyqt4.qsci-dev
      - pyqt5.qsci-dev

before_install:
    - pip install -U setuptools
    - ln -s /usr/lib/python2.7/dist-packages/PySide /usr/lib/python2.7/dist-packages/*dbus* ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install lupa --install-option='--no-luajit'
    - pip install cffi flake8 pyflakes pep8-naming
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - flake8 spreads spreadsplug tests --exclude=vendor
    - py.test --cov spreads --cov spreadsplug -m "not guitest" tests
after_success: coveralls
