language: python
python:
  - "2.7"
  - "3.4"

before_install:
    - pip install -U setuptools
    - sudo add-apt-repository -y ppa:pyside/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq libusb-dev python-pyside libffi-dev libjpeg8-dev libudev-dev libusb-1.0-0-dev python-dbus liblua5.2-dev libusb-dev
    - ln -s /usr/lib/python2.7/dist-packages/PySide /usr/lib/python2.7/dist-packages/*dbus* ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
        sudo apt-get install -qq python3-pyqt4 python3-dbus ;
        export PYTEST_QT_API=pyqt4 ;
        ln -s /usr/lib/python3.2/dist-packages/*dbus* $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/ ;
      fi
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install lupa --install-option='--no-luajit'
    - pip install cffi flake8 pyflakes pep8-naming
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
        flake8 spreads --exclude=vendor --ignore=E226,E241,F821 ;
      else
        flake8 spreads spreadsplug tests --exclude=vendor ;
      fi
    - if [[ $TRAVIS_PYTHON_VERSION != "3.4" ]]; then py.test --cov spreads --cov spreadsplug -m "not guitest" tests ; fi
after_success: coveralls
