language: python
python:
  - "3.4"

before_install:
    - pip install -U setuptools
    - sudo add-apt-repository -y ppa:pyside/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq libusb-dev python-pyside libffi-dev libjpeg8-dev libudev-dev libusb-1.0-0-dev python-dbus liblua5.2-dev python3-pyside python3-pyqt4 python3-dbus
    - export PYTEST_QT_API=pyqt4
    - echo TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - ls -d /usr/lib/python*
    - ls -d ~/virtualenv/python*
    - ln -s /usr/lib/python3.2/dist-packages/PySide /usr/lib/python3.2/dist-packages/*dbus* ~/virtualenv/python3.4.2/lib/python3.4/site-packages/
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install lupa --install-option='--no-luajit'
    - pip install cffi flake8 pyflakes pep8-naming
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - flake8 spreads spreadsplug tests --exclude=vendor
    - py.test --cov spreads --cov spreadsplug -m "not guitest" tests
after_success: coveralls
