language: python
python:
  - "2.7_with_system_site_packages"
addons:
  apt:
    packages:
      - python-tk
      - libusb-dev
      - libusb-1.0-0-dev
      - libudev-dev
      - python-dbus
      - libffi-dev
      - liblua5.2-dev
      - libjpeg8-dev
      - pyqt4-dev-tools
before_install:
    - pip install -U setuptools pytest
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install lupa --install-option='--no-luajit'
    - pip install cffi flake8 pyflakes pep8-naming
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - flake8 spreads spreadsplug tests --exclude=vendor
    - py.test --cov spreads --cov spreadsplug -m "not guitest" tests
after_success: coveralls
